(function(g){var window=this;var jqa=function(a,b){return g.Ub(a,b)},a6=function(){},kqa=function(a){if(a.Bc&&"function"==typeof a.Bc)return a.Bc();
if(g.Da(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},lqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.Da(a))(0,g.y)(a,b,void 0);else{if(a.Pd&&"function"==typeof a.Pd)var c=a.Pd();else if(a.Bc&&"function"==typeof a.Bc)c=void 0;else if(g.La(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=kqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},b6=function(a){g.un(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},c6=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.zn(a.l,b,c)},d6=function(a){return(a=g.So(a))?new ActiveXObject(a):new XMLHttpRequest},e6=function(a,b){return b+" ["+a.Y+" "+a.D+" "+a.getStatus()+"]"},mqa=function(a){return"content-type"==a.toLowerCase()},f6=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.u.clearTimeout(a.F),a.F=null)},nqa=function(a){return g.Ld&&g.ld(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},g6=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},h6=function(a,b){if(a.g){f6(a);
var c=a.g,d=a.R[0]?g.Ha:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},i6=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;g6(a);h6(a)},j6=function(a){return a.g?a.g.readyState:0},k6=function(a){if(a.i&&"undefined"!=typeof g.ZY)if(a.R[1]&&4==j6(a)&&2==a.getStatus())e6(a,"Local request error detected and ignored");
else if(a.B&&4==j6(a))g.Gg(a.ww,0,a);else if(a.dispatchEvent("readystatechange"),4==j6(a)){e6(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!oqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<j6(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";g6(a)}}finally{h6(a)}}},l6=function(a){g.Sf.call(this);
this.headers=new g.jn;this.M=a||null;this.i=!1;this.R=this.g=null;this.Y=this.D="";this.u=0;this.l="";this.o=this.aa=this.B=this.P=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},m6=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},pqa=function(a,b){var c=[];
g.Rk(b,function(d){try{var e=g.gp.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.fp(e)&&c.push(d):c.push(d)},a);
return c},qqa=function(a,b){var c=pqa(a,b);
(0,g.y)(c,function(d){g.gp.prototype.remove.call(this,d)},a)},n6=function(a){if(a.hd){if(a.hd.locationOverrideToken)return{locationOverrideToken:a.hd.locationOverrideToken};
if(null!=a.hd.latitudeE7&&null!=a.hd.longitudeE7)return{latitudeE7:a.hd.latitudeE7,longitudeE7:a.hd.longitudeE7}}return null},rqa=function(a,b){g.$a(a,b)||a.push(b)},o6=function(a){var b=0,c;
for(c in a)b++;return b},p6=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},sqa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},tqa=function(a,b,c,d){var e=new g.mn(null,void 0);
a&&g.nn(e,a);b&&g.on(e,b);c&&g.pn(e,c);d&&(e.i=d);return e},q6=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return sqa(a)},r6=function(){this.g=[];
this.i=[]},s6=function(a,b){g.lq[a]=!0;
var c=g.jq();c&&c.publish.apply(c,arguments);g.lq[a]=!1},t6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.jn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",uqa(this,a.capabilities||""),vqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},uqa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(jqa,wqa)).forEach(function(c){a.capabilities.add(c)})},vqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},u6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},v6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},w6=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},xqa=function(a){return new u6(a)},x6=function(a){return g.Ka(a)?(0,g.ge)(a,xqa):[]},y6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},z6=function(a){return g.Ka(a)?"["+(0,g.ge)(a,y6).join(",")+"]":"null"},A6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},yqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},B6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},C6=function(a,b){return g.Xa(a,function(c){return v6(c,b)})},D6=function(a){try{var b=(0,g.It)(),c=(0,g.Ht)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},zqa=function(){var a=(0,g.Ht)();
a&&qqa(a,a.g.nf(!0))},E6=function(){var a=g.Kt("yt-remote-connected-devices")||[];
g.qb(a);return a},Aqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},F6=function(a){g.Jt("yt-remote-connected-devices",a,86400)},H6=function(){if(G6)return G6;
var a=g.Kt("yt-remote-device-id");a||(a=A6(),g.Jt("yt-remote-device-id",a,31536E3));for(var b=E6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return G6=d},I6=function(){var a=E6(),b=H6();
g.$a(a,b);g.Lt()&&g.sb(a,b);a=Aqa(a);if(0==a.length)try{g.Ms("remote_sid")}catch(c){}else try{g.Ls("remote_sid",a.join(","),-1)}catch(c){}},J6=function(){return g.Kt("yt-remote-session-browser-channel")},K6=function(){return g.Kt("yt-remote-local-screens")||[]},L6=function(){g.Jt("yt-remote-lounge-token-expiration",!0,86400)},Bqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(K6(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.mj)(c,function(d){return!g.$a(b,d)})&&L6();
g.Jt("yt-remote-local-screens",a,31536E3)},Cqa=function(a,b){g.Jt("yt-remote-session-browser-channel",a);
g.Jt("yt-remote-session-screen-id",b);var c=E6(),d=H6();g.$a(c,d)||c.push(d);F6(c);I6()},M6=function(a){a||(D6("yt-remote-session-screen-id"),D6("yt-remote-session-video-id"));
I6();a=E6();g.cb(a,H6());F6(a)},O6=function(){if(!N6){var a=g.qp();
a&&(N6=new g.ap(a))}return N6?!!N6.get("yt-remote-use-staging-server"):!1},P6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Q6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},S6=function(a){a.length?R6(a.shift(),function(){S6(a)}):T6()},Dqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},R6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},T6=function(){var a=Q6();
a&&a(!1,"No cast extension found")},U6=function(){if(Eqa){var a=2,b=Q6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;R6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",T6,c)}},Fqa=function(){U6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);S6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},V6=function(a,b,c){g.A.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Zc=b;this.u=(0,g.x)(this.ED,this);this.g=!1;this.i=0;this.l=this.Aa=null;this.o=[]},W6=function(){},X6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ca=new g.An(this);this.i=new g.Fg;this.i.setInterval(250)},Z6=function(a,b,c){a.Zh=1;
a.ag=b6(b.clone());a.sh=c;a.u=!0;Y6(a,null)},$6=function(a,b,c,d,e){a.Zh=1;
a.ag=b6(b.clone());a.sh=null;a.u=c;e&&(a.oA=!1);Y6(a,d)},Y6=function(a,b){a.Ii=(0,g.D)();
a7(a);a.Eg=a.ag.clone();c6(a.Eg,"t",a.A);a.nl=0;a.wc=a.g.Kp(a.g.Vk()?b:null);0<a.qq&&(a.bo=new g.Jl((0,g.x)(a.uB,a,a.wc),a.qq));a.ca.da(a.wc,"readystatechange",a.xM);var c=a.Zg?g.bc(a.Zg):{};a.sh?(a.Ko="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.wc.send(a.Eg,a.Ko,a.sh,c)):(a.Ko="GET",a.oA&&!g.Nd&&(c.Connection="close"),a.wc.send(a.Eg,a.Ko,null,c));a.g.Be(1)},h7=function(a,b,c){for(var d=!0;!a.Og&&a.nl<c.length;){var e=Gqa(a,c);
if(e==b7){4==b&&(a.rg=4,c7(15),d=!1);break}else if(e==d7){a.rg=4;c7(16);d=!1;break}else e7(a,e)}4==b&&0==c.length&&(a.rg=1,c7(17),d=!1);a.Ee=a.Ee&&d;d||(f7(a),g7(a))},Gqa=function(a,b){var c=a.nl,d=b.indexOf("\n",c);
if(-1==d)return b7;c=Number(b.substring(c,d));if(isNaN(c))return d7;d+=1;if(d+c>b.length)return b7;var e=b.substr(d,c);a.nl=d+c;return e},k7=function(a,b){a.Ii=(0,g.D)();
a7(a);var c=b?window.location.hostname:"";a.Eg=a.ag.clone();g.un(a.Eg,"DOMAIN",c);g.un(a.Eg,"t",a.A);try{a.Ie=new ActiveXObject("htmlfile")}catch(n){f7(a);a.rg=7;c7(22);g7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in i7)k=i7[l];else if(l in j7)k=i7[l]=j7[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
i7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.Ie.open();a.Ie.write(g.Mc(c));a.Ie.close();a.Ie.parentWindow.m=(0,g.x)(a.ML,a);a.Ie.parentWindow.d=(0,g.x)(a.vz,a,!0);a.Ie.parentWindow.rpcClose=(0,g.x)(a.vz,a,!1);c=a.Ie.createElement("DIV");a.Ie.parentWindow.document.body.appendChild(c);d=g.Cc(a.Eg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.Be(1)},a7=function(a){a.At=(0,g.D)()+a.o;
l7(a,a.o)},l7=function(a,b){if(null!=a.Zi)throw Error("WatchDog timer not null");
a.Zi=m7((0,g.x)(a.WL,a),b)},n7=function(a){a.Zi&&(g.u.clearTimeout(a.Zi),a.Zi=null)},g7=function(a){a.g.tw()||a.Og||a.g.On(a)},f7=function(a){n7(a);
g.qf(a.bo);a.bo=null;a.i.stop();g.Cn(a.ca);if(a.wc){var b=a.wc;a.wc=null;b.abort();b.dispose()}a.Ie&&(a.Ie=null)},e7=function(a,b){try{a.g.oz(a,b),a.g.Be(4)}catch(c){}},p7=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;o7(a,b,function(k){k?c(!0):g.u.setTimeout(function(){p7(a,b,c,d,f)},f)})}},o7=function(a,b,c){var d=new Image;
d.onload=function(){try{q7(d),c(!0)}catch(e){}};
d.onerror=function(){try{q7(d),c(!1)}catch(e){}};
d.onabort=function(){try{q7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{q7(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
p6(d,a)},q7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},r7=function(a){this.g=a;
this.i=new W6},t7=function(a){var b=s7(a.g,a.mj,"/mail/images/cleardot.gif");
b6(b);p7(b.toString(),5E3,(0,g.x)(a.LC,a),3,2E3);a.Be(1)},v7=function(a){var b=a.g.F;
if(null!=b)c7(5),b?(c7(11),u7(a.g,a,!1)):(c7(12),u7(a.g,a,!0));else if(a.Hd=new X6(a,void 0,void 0,void 0),a.Hd.Zg=a.nq,b=a.g,b=s7(b,b.Vk()?a.Tj:null,a.oq),c7(5),!g.Ld||g.od(10))c6(b,"TYPE","xmlhttp"),$6(a.Hd,b,!1,a.Tj,!1);else{c6(b,"TYPE","html");var c=a.Hd;a=!!a.Tj;c.Zh=3;c.ag=b6(b.clone());k7(c,a)}},w7=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new W6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},Hqa=function(a,b){this.g=a;
this.map=b;this.context=null},x7=function(a){g.sf.call(this,"statevent",a)},y7=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},z7=function(a){g.sf.call(this,"serverreachability",a)},Kqa=function(a){Iqa(a);
if(3==a.g){var b=a.Ak++,c=a.pm.clone();g.un(c,"SID",a.l);g.un(c,"RID",b);g.un(c,"TYPE","terminate");A7(a,c);b=new X6(a,a.l,b,void 0);b.Zh=2;b.ag=b6(c.clone());p6(new Image,b.ag.toString());b.Ii=(0,g.D)();a7(b)}Jqa(a)},Lqa=function(a){a.eD(1,0);
a.pm=s7(a,null,a.mq);B7(a)},Iqa=function(a){a.hg&&(a.hg.abort(),a.hg=null);
a.Ub&&(a.Ub.cancel(),a.Ub=null);a.qf&&(g.u.clearTimeout(a.qf),a.qf=null);C7(a);a.Ed&&(a.Ed.cancel(),a.Ed=null);a.og&&(g.u.clearTimeout(a.og),a.og=null)},Mqa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new Hqa(a.aI++,b));2!=a.g&&3!=a.g||B7(a)},B7=function(a){a.Ed||a.og||(a.og=m7((0,g.x)(a.uz,a),0),a.Sh=0)},Oqa=function(a,b){if(1==a.g){if(!b){a.Ak=Math.floor(1E5*Math.random());
var c=a.Ak++,d=new X6(a,"",c,void 0);d.Zg=null;var e=D7(a),f=a.pm.clone();g.un(f,"RID",c);g.un(f,"CVER","1");A7(a,f);Z6(d,f,e);a.Ed=d;a.g=2}}else 3==a.g&&(b?Nqa(a,b):0==a.i.length||a.Ed||Nqa(a))},Nqa=function(a,b){if(b)if(6<a.Pg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Ak-1;var d=D7(a)}else c=b.B,d=b.sh;else c=a.Ak++,d=D7(a);var e=a.pm.clone();g.un(e,"SID",a.l);g.un(e,"RID",c);g.un(e,"AID",a.li);A7(a,e);c=new X6(a,a.l,c,a.Sh+1);c.Zg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ed=c;Z6(c,e,d)},A7=function(a,b){if(a.Wc){var c=a.Wc.Sv();
c&&g.Kb(c,function(d,e){g.un(b,e,d)})}},D7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Pg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Pg?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Pqa=function(a){a.Ub||a.qf||(a.B=1,a.qf=m7((0,g.x)(a.sz,a),0),a.Lh=0)},E7=function(a){if(a.Ub||a.qf||3<=a.Lh)return!1;
a.B++;a.qf=m7((0,g.x)(a.sz,a),Qqa(a,a.Lh));a.Lh++;return!0},u7=function(a,b,c){a.Io=c;
a.Ne=b.Bf;a.A||Lqa(a)},C7=function(a){null!=a.Tg&&(g.u.clearTimeout(a.Tg),a.Tg=null)},Qqa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},F7=function(a,b){if(2==b||9==b){var c=null;
a.Wc&&(c=null);var d=(0,g.x)(a.dN,a);c||(c=new g.mn("//www.google.com/images/cleardot.gif"),b6(c));o7(c.toString(),1E4,d)}else c7(2);Rqa(a,b)},Rqa=function(a,b){a.g=0;
a.Wc&&a.Wc.Uu(b);Jqa(a);Iqa(a)},Jqa=function(a){a.g=0;
a.Ne=-1;if(a.Wc)if(0==a.o.length&&0==a.i.length)a.Wc.yp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Wc.yp(b)}},s7=function(a,b,c){var d=g.vn(c);
if(""!=d.g)b&&g.on(d,b+"."+d.g),g.pn(d,d.u);else{var e=window.location;d=tqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Bj&&g.Kb(a.Bj,function(f,k){g.un(d,k,f)});
g.un(d,"VER",a.Pg);A7(a,d);return d},m7=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},c7=function(a){G7.dispatchEvent(new x7(G7,a))},Sqa=function(){},Tqa=function(a,b){this.action=a;
this.params=b||{}},H7=function(a,b){g.A.call(this);
this.g=new g.J(this.EL,0,this);g.B(this,this.g);this.Zc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},I7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.$o;this.i=new H7(this.HM,this);this.g=null;this.jb=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},Uqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Io,sessionId:a.g.l,arrayId:a.g.li}},Vqa=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&Oqa(a.g),Kqa(a.g));a.D=0},J7=function(a){return!!a.g&&3==a.g.g},Wqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},K7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},L7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.bh(c+b,{})},M7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),oe:g.Qa(a.u,e)};c&&(a.wb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.dr(b,a)},$qa=function(){var a=Xqa;
Yqa();N7.push(a);Zqa(N7)},O7=function(a,b){Yqa();
var c=N7,d=ara(a,String(b));0==c.length?bra(d):(Zqa(c),(0,g.y)(c,function(e){e(d)}))},Yqa=function(){N7||(N7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",N7,void 0))},bra=function(a){var b=(P7+1)%50;
P7=b;Q7[b]=a;R7||(R7=49==b)},Zqa=function(a){var b=Q7;
if(b[0]){var c=P7,d=R7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
Q7=Array(50);P7=-1;R7=!1}},ara=function(a,b){var c=((0,g.D)()-cra)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},S7=function(a){g.N.call(this);
this.B=a;this.g=[]},dra=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},era=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!B6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=dra(a,b[d])||c;return c},fra=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},T7=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Aa=NaN},V7=function(a){S7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;U7(this);this.info("Initializing with "+z6(this.g))},gra=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=L7(a.l,"/pairing/get_lounge_token_batch");
M7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.OD,a),(0,g.x)(a.ND,a))}},U7=function(a){var b=x6(K6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return era(a,b)},W7=function(a,b){Bqa((0,g.ge)(a.g,w6));
b&&L6()},Y7=function(a,b){g.N.call(this);
this.A=b;var c=g.Kt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;X7("Initialized with "+g.Kg(this.g))},hra=function(a,b,c){var d=L7(a.u,"/pairing/get_screen_availability");
M7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},Z7=function(a,b){a:if(o6(b)!=o6(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(X7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.N("screenChange"));ira(a)},$7=function(a){isNaN(a.l)||g.iq(a.l);
a.l=g.gq((0,g.x)(a.Es,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},X7=function(a){O7("OnlineScreenService",a)},jra=function(a){var b={};
(0,g.y)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},ira=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Jt("yt-remote-online-screen-ids",a.join(","),60):D6("yt-remote-online-screen-ids")},a8=function(a){S7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};kra(this)},mra=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Rd();if(k=(c?C6(k,c):null)||C6(k,b)){k.uuid=b;var l=b8(a,k);hra(a.i,l,function(m){e(m?l:null)})}else c?lra(a,c,(0,g.x)(function(m){var n=b8(this,new u6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));hra(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},nra=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},lra=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={wb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.dr(L7(a.A,"/pairing/get_lounge_token_batch"),e)},ora=function(a){a.g=a.l.Rd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+z6(a.g))},kra=function(a){c8(a);
a.l=new V7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.WD,a));ora(a);a.o=x6(g.Kt("yt-remote-automatic-screen-cache")||[]);c8(a);a.info("Initializing automatic screens: "+z6(a.o));a.i=new Y7(a.A,(0,g.x)(a.Rd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},b8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=C6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Jt("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,w6)));c8(a);a.u[b.uuid]=b.id;g.Jt("yt-remote-device-id-map",a.u,31536E3);return b},c8=function(a){a.u=g.Kt("yt-remote-device-id-map")||{}},d8=function(a,b,c){g.N.call(this);
this.R=c;this.F=a;this.i=b;this.l=null},e8=function(a,b){O7(a.R,b)},f8=function(a,b){d8.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.IN,this);this.u=(0,g.x)(this.hM,this);this.o=g.gq((0,g.x)(function(){pra(this,null)},this),12E4)},qra=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){e8(this,"Failed to send message: getMdxSessionStatus.")},a)):e8(a,"Sending yt message without session: "+g.Kg(b))},pra=function(a,b){g.iq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.Qn,a),d=(0,g.x)(a.Ud,a);a.kw(b,c,d,5)}}else a.Ud(Error("Waiting for session status timed out."))},g8=function(a,b,c){d8.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ha;this.A=NaN;this.I=(0,g.x)(this.LN,this);this.g=g.Ha},rra=function(a){a.g=a.F.zB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.Qn(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Ud(b)},a))},sra=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}O6()&&(b.env_useStageMdx=1);return g.$g(b)},h8=function(a,b){d8.call(this,a,b,"ManualSession");
this.g=g.gq((0,g.x)(this.ni,this,null),150)},i8=function(a,b,c,d){g.N.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.MK,this)},tra=function(a,b){return b?g.Xa(a.l,function(c){return v6(b,c.label)},a):null},j8=function(a){O7("Controller",a)},Xqa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},k8=function(a){return a.u||!!a.l.length||!!a.g},l8=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.rz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ni(null)):a.N("yt-remote-cast2-session-change",null))},ura=function(a){var b=a.i.yB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&v6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=tra(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Ara=function(a,b,c,d,e,f,k){vra()?wra(b,e,f,k)&&(n8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?xra(a,c):(window.__onGCastApiAvailable=function(l,m){l?xra(a,c):(o8("Failed to load cast API: "+m),p8(!1),n8(!1),D6("yt-remote-cast-available"),D6("yt-remote-cast-receiver"),yra(),c(!1))},d?g.tq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Fqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?T6():(U6(),S6(zra.map(Dqa))))):m8("Cannot initialize because not running Chrome")},yra=function(){m8("dispose");
var a=q8();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Bra(!1);g.oq(r8);r8.length=0},s8=function(){return!!g.Kt("yt-remote-cast-installed")},Cra=function(){var a=g.Kt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Dra=function(){m8("clearCurrentReceiver");
D6("yt-remote-cast-receiver")},Era=function(){return s8()?q8()?q8().getCastSession():(o8("getCastSelector: Cast is not initialized."),null):(o8("getCastSelector: Cast API is not installed!"),null)},u8=function(){s8()?q8()?t8()?(m8("Requesting cast selector."),q8().requestSession()):(m8("Wait for cast API to be ready to request the session."),r8.push(g.nq("yt-remote-cast2-api-ready",u8))):o8("requestCastSelector: Cast is not initialized."):o8("requestCastSelector: Cast API is not installed!")},v8=
function(a,b){t8()?q8().setConnectedScreenStatus(a,b):o8("setConnectedScreenStatus called before ready.")},vra=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.sx||a},Fra=function(a,b){q8().init(a,b)},wra=function(a,b,c,d){var e=!1;
q8()||(a=new i8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Jt("yt-remote-cast-available",f);s6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){m8("onReceiverSelected: "+f.friendlyName);
g.Jt("yt-remote-cast-receiver",f);s6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){m8("onReceiverResumed: "+f.friendlyName);
g.Jt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){m8("onSessionChange: "+y6(f));
f||D6("yt-remote-cast-receiver");s6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
m8("cloudview.createSingleton_: "+e);return e},q8=function(){return g.w("yt.mdx.remote.cloudview.instance_")},xra=function(a,b){p8(!0);
n8(!1);Fra(a,function(c){c?(Bra(!0),g.qq("yt-remote-cast2-api-ready")):(o8("Failed to initialize cast API."),p8(!1),D6("yt-remote-cast-available"),D6("yt-remote-cast-receiver"),yra());b(c)})},m8=function(a){O7("cloudview",a)},o8=function(a){O7("cloudview",a)},p8=function(a){m8("setCastInstalled_ "+a);
g.Jt("yt-remote-cast-installed",a)},t8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Bra=function(a){m8("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},n8=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},w8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Oe=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},x8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Oe=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},y8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},z8=function(a,b){a.B=b;
a.A=(0,g.D)()},A8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},B8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&x8(a)},C8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Oe;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},E8=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new r6;this.l=this.i=null;this.F=(0,g.x)(this.JI,this);this.B=(0,g.x)(this.Dk,this);this.D=(0,g.x)(this.II,this);this.H=(0,g.x)(this.XI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Dt,this),Gra(this))):c=3;0!=c&&(b?this.Dt(c):g.gq((0,g.x)(function(){this.Dt(c)},this),0));
var d=Era();d&&D8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},F8=function(a){return new w8(a.o.getPlayerContextData())},Gra=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.JK,b),this))},a)},Hra=function(a){(0,g.y)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},G8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},I8=function(a,b,c){var d=F8(a);
z8(d,c);-1E3!=d.playerState&&(d.playerState=b);H8(a,d)},J8=function(a,b,c){a.o.sendMessage(b,c)},H8=function(a,b){Hra(a);
a.o.setPlayerContextData(C8(b));Gra(a)},D8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.Dk(null));
a.l=b;a.l&&(O7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.Dk(a.l.media[0]))},Ira=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=F8(a);b.contentId!=d.videoId&&O7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;z8(d,a.i.getEstimatedTime());H8(a,d)}else O7("CP","No cast media video. Ignoring state update.")},K8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),J8(this,b,c))},a)},L8=function(a,b,c){g.N.call(this);
this.u=NaN;this.I=!1;this.D=this.B=this.F=this.H=NaN;this.R=[];this.o=this.A=this.l=this.Qa=this.g=null;this.P=a;this.R.push(g.ms(window,"beforeunload",(0,g.x)(this.HD,this)));this.i=[];this.Qa=new w8;this.M=b.id;this.g=Jra(this,c);this.g.subscribe("handlerOpened",this.NI,this);this.g.subscribe("handlerClosed",this.KI,this);this.g.subscribe("handlerError",this.LI,this);this.g.subscribe("handlerMessage",this.MI,this);Wqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.Lt()&&g.Jt("yt-remote-session-video-id",d)},this)},M8=function(a){O7("conn",a)},Jra=function(a,b){return new I7(L7(a.P,"/bc"),b)},N8=function(a,b){a.N("proxyStateChange",b)},Kra=function(a){a.u=g.gq((0,g.x)(function(){M8("Connecting timeout");
this.Ph(1)},a),2E4)},O8=function(a){g.iq(a.u);
a.u=NaN},P8=function(a){g.iq(a.H);
a.H=NaN},Lra=function(a){Q8(a);
a.F=g.gq((0,g.x)(function(){R8(this,"getNowPlaying")},a),2E4)},Q8=function(a){g.iq(a.F);
a.F=NaN},Nra=function(a,b){b&&(O8(a),P8(a));
b==(J7(a.g)&&isNaN(a.u))?b&&(N8(a,1),R8(a,"getSubtitlesTrack")):b?(a.iw()&&a.Qa.reset(),N8(a,1),R8(a,"getNowPlaying"),Mra(a)):a.Ph(1)},Ora=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Xb(b.params)?a.Qa.g=null:a.Qa.g=b.params,a.N("remotePlayerChange"))},Pra=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;B8(a.Qa,c,d);a.N("remoteQueueChange")},Rra=function(a,b){b.params=b.params||{};
Pra(a,b);Qra(a,b);a.N("autoplayDismissed")},Qra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
z8(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.D=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Qa.playerState?Lra(a):Q8(a);a.N("remotePlayerChange")},Sra=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);z8(a.Qa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Tra=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.N("remotePlayerChange")},Ura=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Vra=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Oe="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.N("previousNextChange")},Mra=function(a){g.iq(a.D);
a.D=g.gq((0,g.x)(a.Ph,a,1),864E5)},R8=function(a,b,c){c?M8("Sending: action="+b+", params="+g.Kg(c)):M8("Sending: action="+b);
a.g.sendMessage(b,c)},S8=function(a){S7.call(this,"ScreenServiceProxy");
this.Yc=a;this.i=[];this.i.push(this.Yc.$_s("screenChange",(0,g.x)(this.GN,this)));this.i.push(this.Yc.$_s("onlineScreenChange",(0,g.x)(this.oK,this)))},$ra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Zp("MDX_CONFIG")||b;zqa();I6();T8||(T8=new K7(b?b.loungeApiHost:void 0),O6()&&(T8.g="/api/loungedev"));U8||(U8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",U8,void 0));Wra();var c=V8();if(!c){var d=new a8(T8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=V8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Ara(a,d,function(m){m?W8()&&v8(W8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){s6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),X8("Initializing: "+g.Kg(b)),Y8.push(g.nq("yt-remote-cast2-availability-change",function(){s6("yt-remote-receiver-availability-change")})),Y8.push(g.nq("yt-remote-cast2-receiver-selected",function(){Z8(null);
s6("yt-remote-auto-connect","cast-selector-receiver")})),Y8.push(g.nq("yt-remote-cast2-receiver-resumed",function(){s6("yt-remote-receiver-resumed","cast-selector-receiver")})),Y8.push(g.nq("yt-remote-cast2-session-change",Xra)),Y8.push(g.nq("yt-remote-connection-change",function(m){m?v8(W8(),"YouTube TV"):$8()||(v8(null,null),Dra())})),a=a9(),b.isAuto&&(a.id+="#dial"),g.Vq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),X8(" -- with channel params: "+
g.Kg(a)),Yra(a),c.start(),W8()||Zra())},bsa=function(){var a=asa();
s8()&&g.Kt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},asa=function(){var a=V8().Yc.$_gos();
var b=b9();b&&c9()&&(B6(a,b)||a.push(b));return yqa(a)},d9=function(){var a=csa();
!a&&s8()&&Cra()&&(a={key:"cast-selector-receiver",name:Cra()});return a},csa=function(){var a=asa(),b=b9();
b||(b=$8());return g.Xa(a,function(c){return b&&v6(b,c.key)?!0:!1})},b9=function(){var a=W8();
if(!a)return null;var b=V8().Rd();return C6(b,a)},Xra=function(a){X8("remote.onCastSessionChange_: "+y6(a));
if(a){var b=b9();b&&b.id==a.id?v8(b.id,"YouTube TV"):(b&&e9(),f9(a,1))}else c9()&&e9()},e9=function(){t8()?q8().stopSession():o8("stopSession called before API ready.");
var a=c9();a&&(a.disconnect(1),g9(null))},h9=function(){var a=c9();
return!!a&&3!=a.getProxyState()},X8=function(a){O7("remote",a)},V8=function(){if(!i9){var a=g.w("yt.mdx.remote.screenService_");
i9=a?new S8(a):null}return i9},W8=function(){return g.w("yt.mdx.remote.currentScreenId_")},dsa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},esa=function(){return g.w("yt.mdx.remote.connectData_")},Z8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},c9=function(){return g.w("yt.mdx.remote.connection_")},g9=function(a){var b=c9();
Z8(null);a||dsa("");g.Ga("yt.mdx.remote.connection_",a,void 0);U8&&((0,g.y)(U8,function(c){c(a)}),U8.length=0);
b&&!a?s6("yt-remote-connection-change",!1):!b&&a&&s6("yt-remote-connection-change",!0)},$8=function(){var a=g.Lt();
if(!a)return null;var b=V8().Rd();return C6(b,a)},f9=function(a,b){b9()&&b9();
if(j9)k9=a;else{dsa(a.id);var c=new L8(T8,a,a9());c.connect(b,esa());c.subscribe("beforeDisconnect",function(d){s6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){c9()&&g9(null)});
g9(c)}},Zra=function(){var a=$8();
a?(X8("Resume connection to: "+y6(a)),f9(a,0)):(M6(),Dra(),X8("Skipping connecting because no session screen found."))},Wra=function(){var a=a9();
if(g.Xb(a)){a=H6();var b=g.Kt("yt-remote-session-name")||"",c=g.Kt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},a9=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Yra=function(a){a?(g.Jt("yt-remote-session-app",a.app),g.Jt("yt-remote-session-name",a.name)):(D6("yt-remote-session-app"),D6("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},l9=function(a,b,c){g.A.call(this);
this.u=a;this.i=b;this.l=new g.Ws(this);g.B(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.JJ);this.l.K(b,"captionschanged",this.HI);this.l.K(b,"captionssettingschanged",this.MA);this.l.K(b,"videoplayerreset",this.Rn);this.l.K(b,"mdxautoplaycancel",this.KC);this.P=this.l.K(b,"onVolumeChange",this.bz);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.nz,this);c.subscribe("remotePlayerChange",this.Fk,this);c.subscribe("remoteQueueChange",this.Rn,this);c.subscribe("autoplayUpNext",this.Py,
this);c.subscribe("previousNextChange",this.kz,this);c.subscribe("nowAutoplaying",this.gz,this);c.subscribe("autoplayDismissed",this.Oy,this);this.suggestion=null;this.F=new g.RC(64);this.o=new g.J(this.KA,500,this);g.B(this,this.o);this.A=new g.J(this.LA,1E3,this);g.B(this,this.A);this.I=new V6(this.mN,0,this);g.B(this,this.I);this.B={};this.R=new g.J(this.mB,1E3,this);g.B(this,this.R);this.H=new g.Jl(this.eG,1E3,this);g.B(this,this.H);this.M=g.Ha;this.MA();this.Rn();this.Fk()},m9=function(a,b){a.u.Nc(b,
a.i.getVideoData().lengthSeconds)},fsa=function(a){m9(a,0);
a.o.stop();n9(a,new g.RC(64))},p9=function(a,b){if(o9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.BA(a.i.getVideoData(1).videoId,c);a.B=F8(a.g).g}},q9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Gf,n6(c));n9(a,new g.RC(1))},gsa=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{kR:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},o9=function(a){return F8(a.g).videoId==a.i.getVideoData(1).videoId},n9=function(a,b){a.A.stop();
var c=a.F;if(!g.XC(c,b)){var d=g.T(b,2);d!=g.T(a.F,2)&&g.OK(a.i,d);a.F=b;hsa(a.u,c,b)}},r9=function(){g.V.call(this,{C:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{C:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{C:"div",G:"ytp-mdx-popup-title",V:"You're signed out"},{C:"div",G:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{C:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.l=new g.IQ(this,250);g.B(this,this.l);this.B=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.B,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},s9=function(a){g.V.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.XP()]},{C:"div",G:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.IQ(this,250);g.B(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);isa(this,g.KK(a))},isa=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.WN("Error on $RECEIVER_NAME",c):g.YC(b)||g.T(b,4)?g.WN("Playing on $RECEIVER_NAME",c):g.WN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},t9=function(a,b){g.tU.call(this,"Play on",0,a,b);
this.l=a;this.B={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},u9=function(a){g.oL.call(this,a);
this.i={key:A6(),name:"This computer"};this.u=null;this.o=[];this.F=this.g=null;this.B=[this.i];this.l=this.i;this.nk=new g.RC(64);this.I=0;this.Um=-1;if(!g.xz(g.X(this.player))){a=this.player;var b=g.KD(a);b&&(b=b.zn())&&(b=new t9(a,b),g.B(this,b));b=new s9(a);g.B(this,b);g.ZK(a,b.element,4);this.H=new r9;g.B(this,this.H);g.ZK(a,this.H.element,4);this.D=!!$8()}this.A=null},v9=function(a){a.A&&(a.player.removeEventListener("presentingplayerstatechange",a.A),a.A=null)},hsa=function(a,b,c){a.nk=c;
a.player.N("presentingplayerstatechange",new g.aE(c,b))},w9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)e9();
else{var c;if(c=g.O(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))c=g.Zp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Zp("SESSION_INDEX")||g.Zp("LOGGED_IN"));c&&!a.D&&(g.YC(g.KK(a.player))||(a.A=(0,g.x)(a.oM,a),a.player.addEventListener("presentingplayerstatechange",a.A)),a.player.pauseVideo(),a.H.l.show(),c9()||(j9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<
f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Gf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=n6(c))&&(d.locationInfo=c);c=d}else c=null;X8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(Z8(c||null),t8()?q8().setLaunchParams(c||null):o8("setLaunchParams called before ready.")):!c&&h9()&&W8()==b.key?s6("yt-remote-connection-change",!0):(e9(),
Z8(c||null),c=V8().Rd(),(c=C6(c,b.key))&&f9(c,1))}},oqa=/^https?$/i,jsa=["POST",
"PUT"];g.Sa(l6,g.Sf);g.h=l6.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.Y=b;this.P=!1;this.i=!0;this.g=this.M?d6(this.M):d6(g.wZ);this.R=this.M?this.M.getOptions():g.wZ.getOptions();this.g.onreadystatechange=(0,g.x)(this.ww,this);try{a6(e6(this,"Opening Xhr")),this.aa=!0,this.g.open(b,String(a),!0),this.aa=!1}catch(f){a6(e6(this,"Error opening Xhr: "+f.message));i6(this,f);return}a=
c||"";var e=this.headers.clone();d&&lqa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Pd(),mqa);c=g.u.FormData&&a instanceof g.u.FormData;!g.$a(jsa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{f6(this),0<this.A&&(this.I=nqa(this.g),a6(e6(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.xw,this)):this.F=g.Gg(this.xw,this.A,this)),a6(e6(this,"Sending request")),this.B=!0,this.g.send(a),this.B=!1}catch(f){a6(e6(this,"Send error: "+f.message)),i6(this,f)}};
g.h.xw=function(){"undefined"!=typeof g.ZY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,e6(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(e6(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),h6(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),h6(this,!0));l6.fb.U.call(this)};
g.h.ww=function(){this.fa()||(this.aa||this.B||this.o?k6(this):this.LK())};
g.h.LK=function(){k6(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<j6(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.l)?this.l:String(this.l)};
var j7={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},i7={"'":"\\'"},ksa={};g.h=r6.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Vma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.Bc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var wqa={fO:"atp",vQ:"ska",kQ:"que",KP:"mus",uQ:"sus",bP:"dsp",rQ:"seq"};t6.prototype.jg=function(){var a=new t6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var N6,G6="",Eqa=P6("loadCastFramework")||P6("loadCastApplicationFramework"),zra=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(V6,g.A);g.h=V6.prototype;g.h.DD=function(a){this.o=arguments;this.g=!1;this.Aa?this.l=(0,g.D)()+this.Zc:this.Aa=g.Gg(this.u,this.Zc)};
g.h.stop=function(){this.Aa&&(g.u.clearTimeout(this.Aa),this.Aa=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();V6.fb.U.call(this)};
g.h.ED=function(){this.l?(this.Aa=g.Gg(this.u,this.l-(0,g.D)()),this.l=null):(this.Aa=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};W6.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
W6.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};g.h=X6.prototype;g.h.Zg=null;g.h.Ee=!1;g.h.Zi=null;g.h.At=null;g.h.Ii=null;g.h.Zh=null;g.h.ag=null;g.h.Eg=null;g.h.sh=null;g.h.wc=null;g.h.nl=0;g.h.Ie=null;g.h.Ko=null;g.h.rg=null;g.h.Uj=-1;g.h.oA=!0;g.h.Og=!1;g.h.qq=0;g.h.bo=null;var d7={},b7={};g.h=X6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.xM=function(a){a=a.target;var b=this.bo;b&&3==j6(a)?b.Qj():this.uB(a)};
g.h.uB=function(a){try{if(a==this.wc)a:{var b=j6(this.wc),c=this.wc.u,d=this.wc.getStatus();if(g.Ld&&!g.od(10)||g.Nd&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!m6(this.wc))break a;this.Og||4!=b||7==c||(8==c||0>=d?this.g.Be(3):this.g.Be(2));n7(this);var e=this.wc.getStatus();this.Uj=e;var f=m6(this.wc);(this.Ee=200==e)?(4==b&&f7(this),this.u?(h7(this,b,f),g.Ch&&this.Ee&&3==b&&(this.ca.da(this.i,"tick",this.rM),this.i.start())):e7(this,f),this.Ee&&!this.Og&&(4==b?this.g.On(this):(this.Ee=
!1,a7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.rg=3,c7(13)):(this.rg=0,c7(14)),f7(this),g7(this))}}catch(k){this.wc&&m6(this.wc)}finally{}};
g.h.rM=function(){var a=j6(this.wc),b=m6(this.wc);this.nl<b.length&&(n7(this),h7(this,a,b),this.Ee&&4!=a&&a7(this))};
g.h.ML=function(a){m7((0,g.x)(this.LL,this,a),0)};
g.h.LL=function(a){this.Og||(n7(this),e7(this,a),a7(this))};
g.h.vz=function(a){m7((0,g.x)(this.KL,this,a),0)};
g.h.KL=function(a){this.Og||(f7(this),this.Ee=a,this.g.On(this),this.g.Be(4))};
g.h.cancel=function(){this.Og=!0;f7(this)};
g.h.WL=function(){this.Zi=null;var a=(0,g.D)();0<=a-this.At?(2!=this.Zh&&this.g.Be(3),f7(this),this.rg=2,c7(18),g7(this)):l7(this,this.At-a)};
g.h.getLastError=function(){return this.rg};g.h=r7.prototype;g.h.nq=null;g.h.Hd=null;g.h.co=!1;g.h.uw=null;g.h.nm=null;g.h.Xq=null;g.h.oq=null;g.h.he=null;g.h.Bf=-1;g.h.Tj=null;g.h.mj=null;g.h.connect=function(a){this.oq=a;a=s7(this.g,null,this.oq);c7(3);this.uw=(0,g.D)();var b=this.g.D;null!=b?(this.Tj=b[0],(this.mj=b[1])?(this.he=1,t7(this)):(this.he=2,v7(this))):(c6(a,"MODE","init"),this.Hd=new X6(this,void 0,void 0,void 0),this.Hd.Zg=this.nq,$6(this.Hd,a,!1,null,!0),this.he=0)};
g.h.LC=function(a){if(a)this.he=2,v7(this);else{c7(4);var b=this.g;b.Ne=b.hg.Bf;F7(b,9)}a&&this.Be(2)};
g.h.Kp=function(a){return this.g.Kp(a)};
g.h.abort=function(){this.Hd&&(this.Hd.cancel(),this.Hd=null);this.Bf=-1};
g.h.tw=function(){return!1};
g.h.oz=function(a,b){this.Bf=a.Uj;if(0==this.he)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ne=this.Bf;F7(c,2);return}this.Tj=c[0];this.mj=c[1]}else c=this.g,c.Ne=this.Bf,F7(c,2);else if(2==this.he)if(this.co)c7(7),this.Xq=(0,g.D)();else if("11111"==b){if(c7(6),this.co=!0,this.nm=(0,g.D)(),c=this.nm-this.uw,!g.Ld||g.od(10)||500>c)this.Bf=200,this.Hd.cancel(),c7(12),u7(this.g,this,!0)}else c7(8),this.nm=this.Xq=(0,g.D)(),this.co=!1};
g.h.On=function(){this.Bf=this.Hd.Uj;if(this.Hd.Ee)0==this.he?this.mj?(this.he=1,t7(this)):(this.he=2,v7(this)):2==this.he&&((!g.Ld||g.od(10)?!this.co:200>this.Xq-this.nm)?(c7(11),u7(this.g,this,!1)):(c7(12),u7(this.g,this,!0)));else{0==this.he?c7(9):2==this.he&&c7(10);var a=this.g;this.Hd.getLastError();a.Ne=this.Bf;F7(a,2)}};
g.h.Vk=function(){return this.g.Vk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Be=function(a){this.g.Be(a)};g.h=w7.prototype;g.h.Bj=null;g.h.Ed=null;g.h.Ub=null;g.h.mq=null;g.h.pm=null;g.h.Iu=null;g.h.Dm=null;g.h.Ak=0;g.h.aI=0;g.h.Wc=null;g.h.og=null;g.h.qf=null;g.h.Tg=null;g.h.hg=null;g.h.Io=null;g.h.li=-1;g.h.fx=-1;g.h.Ne=-1;g.h.Sh=0;g.h.Lh=0;g.h.Pg=8;var G7=new g.Sf;g.Sa(x7,g.sf);g.Sa(y7,g.sf);g.Sa(z7,g.sf);g.h=w7.prototype;g.h.connect=function(a,b,c,d,e){c7(0);this.mq=b;this.Bj=c||{};d&&g.Ca(e)&&(this.Bj.OSID=d,this.Bj.OAID=e);this.A?(m7((0,g.x)(this.cv,this,a),100),Lqa(this)):this.cv(a)};
g.h.cv=function(a){this.hg=new r7(this);this.hg.nq=null;this.hg.i=this.u;this.hg.connect(a)};
g.h.tw=function(){return 0==this.g};
g.h.uz=function(a){this.og=null;Oqa(this,a)};
g.h.sz=function(){this.qf=null;this.Ub=new X6(this,this.l,"rpc",this.B);this.Ub.Zg=null;this.Ub.qq=0;var a=this.Iu.clone();g.un(a,"RID","rpc");g.un(a,"SID",this.l);g.un(a,"CI",this.Io?"0":"1");g.un(a,"AID",this.li);A7(this,a);if(!g.Ld||g.od(10))g.un(a,"TYPE","xmlhttp"),$6(this.Ub,a,!0,this.Dm,!1);else{g.un(a,"TYPE","html");var b=this.Ub,c=!!this.Dm;b.Zh=3;b.ag=b6(a.clone());k7(b,c)}};
g.h.oz=function(a,b){if(0!=this.g&&(this.Ub==a||this.Ed==a))if(this.Ne=a.Uj,this.Ed==a&&3==this.g)if(7<this.Pg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Ub)if(this.Ub.Ii+3E3<this.Ed.Ii)C7(this),this.Ub.cancel(),this.Ub=null;else break a;E7(this);c7(19)}}else this.fx=c[1],0<this.fx-this.li&&37500>c[2]&&this.Io&&0==this.Lh&&!this.Tg&&(this.Tg=m7((0,g.x)(this.CI,this),6E3));else F7(this,11)}else b!=ksa.CO.g&&F7(this,11);else if(this.Ub==a&&
C7(this),!g.wb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.li=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Dm=e[2],e=e[3],null!=e?this.Pg=e:this.Pg=6,this.g=3,this.Wc&&this.Wc.Wu(),this.Iu=s7(this,this.Vk()?this.Dm:null,this.mq),Pqa(this)):"stop"==e[0]&&F7(this,7):3==this.g&&("stop"==e[0]?F7(this,7):"noop"!=e[0]&&this.Wc&&this.Wc.Vu(e),this.Lh=0)}}};
g.h.CI=function(){null!=this.Tg&&(this.Tg=null,this.Ub.cancel(),this.Ub=null,E7(this),c7(20))};
g.h.On=function(a){if(this.Ub==a){C7(this);this.Ub=null;var b=2}else if(this.Ed==a)this.Ed=null,b=1;else return;this.Ne=a.Uj;if(0!=this.g)if(a.Ee)1==b?(b=(0,g.D)()-a.Ii,G7.dispatchEvent(new y7(G7,a.sh?a.sh.length:0,b,this.Sh)),B7(this),this.o.length=0):Pqa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ne)){if(d=1==b)this.Ed||this.og||1==this.g||2<=this.Sh?d=!1:(this.og=m7((0,g.x)(this.uz,this,a),Qqa(this,this.Sh)),this.Sh++,d=!0);d=!(d||2==b&&E7(this))}if(d)switch(c){case 1:F7(this,
5);break;case 4:F7(this,10);break;case 3:F7(this,6);break;case 7:F7(this,12);break;default:F7(this,2)}}};
g.h.eD=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.dN=function(a){a?c7(2):(c7(1),Rqa(this,8))};
g.h.Kp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new l6;a.T=!1;return a};
g.h.isActive=function(){return!!this.Wc&&this.Wc.isActive(this)};
g.h.Be=function(a){G7.dispatchEvent(new z7(G7,a))};
g.h.Vk=function(){return!(!g.Ld||g.od(10))};
g.h=Sqa.prototype;g.h.Wu=function(){};
g.h.Vu=function(){};
g.h.Uu=function(){};
g.h.yp=function(){};
g.h.Sv=function(){return{}};
g.h.isActive=function(){return!0};g.Sa(H7,g.A);g.h=H7.prototype;g.h.EL=function(){this.Zc=Math.min(3E5,2*this.Zc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Zc+15E3*Math.random();g.Fo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Zc=5E3};g.Sa(I7,Sqa);g.h=I7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Mf=function(a){return this.l.ah(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.jb||(this.jb=!0,g.qf(this.l),Vqa(this),g.qf(this.i),this.i=null)};
g.h.fa=function(){return this.jb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new w7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Wc=null);d.Wc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.li):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):J7(this)&&Mqa(this.g,c)};
g.h.Wu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)Mqa(this.g,a[b])}this.N("handlerOpened")};
g.h.Uu=function(a){var b=2==a&&401==this.g.Ne;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.yp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.Sv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.Vu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),Kqa(this.g)):this.N("handlerMessage",new Tqa(a[0],a[1]))};
g.h.HM=function(){this.i.isActive();var a=this.g,b=0;a.Ub&&b++;a.Ed&&b++;0==b&&this.connect(this.u,this.o)};K7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
K7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
K7.prototype.u=function(a){a(Error("request timed out"))};var cra=(0,g.D)(),N7=null,Q7=Array(50),P7=-1,R7=!1;g.Sa(S7,g.N);S7.prototype.Rd=function(){return this.g};
S7.prototype.contains=function(a){return!!B6(this.g,a)};
S7.prototype.get=function(a){return a?C6(this.g,a):null};
S7.prototype.info=function(a){O7(this.B,a)};g.t(T7,g.N);g.h=T7.prototype;g.h.start=function(){!this.g&&isNaN(this.Aa)&&this.xB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Aa)||(g.iq(this.Aa),this.Aa=NaN)};
g.h.U=function(){this.stop();g.N.prototype.U.call(this)};
g.h.xB=function(){this.Aa=NaN;this.g=g.dr(L7(this.A,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.EN,this),onError:(0,g.x)(this.DN,this),oe:(0,g.x)(this.FN,this)})};
g.h.EN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new u6(c))};
g.h.DN=function(a){this.g=null;a.status&&404==a.status?this.i>=lsa.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=lsa[this.i],this.Aa=g.gq((0,g.x)(this.xB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.FN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var lsa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(V7,S7);g.h=V7.prototype;g.h.start=function(){U7(this)&&this.N("screenChange");!g.Kt("yt-remote-lounge-token-expiration")&&gra(this);g.iq(this.i);this.i=g.gq((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){U7(this);dra(this,a);W7(this,!1);this.N("screenChange");b(a);a.token||gra(this)};
g.h.remove=function(a,b){var c=U7(this);fra(this,a)&&(W7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Eo=function(a,b,c,d){var e=U7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,W7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.iq(this.i);V7.fb.U.call(this)};
g.h.OD=function(a){U7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}W7(this,!b);b&&O7(this.B,"Missed "+b+" lounge tokens.")};
g.h.ND=function(a){O7(this.B,"Requesting lounge tokens failed: "+a)};g.t(Y7,g.N);g.h=Y7.prototype;g.h.start=function(){var a=parseInt(g.Kt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?$7(this):(this.o=(0,g.D)()+3E5,g.Jt("yt-remote-fast-check-period",this.o),this.Es())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){X7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!C6(a,d)},this);
Z7(this,b)};
g.h.U=function(){g.iq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.N.prototype.U.call(this)};
g.h.Es=function(){g.iq(this.l);this.l=NaN;this.i&&this.i.abort();var a=jra(this);if(o6(a)){var b=L7(this.u,"/pairing/get_screen_availability");this.i=M7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.hL,this,a),(0,g.x)(this.gL,this))}else Z7(this,{}),$7(this)};
g.h.hL=function(a,b){this.i=null;var c=g.Rb(jra(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Z7(this,d);$7(this)}else this.Hb("Changing Screen set during request."),this.Es()};
g.h.gL=function(a){this.Hb("Screen availability failed: "+a);this.i=null;$7(this)};
g.h.Hb=function(a){O7("OnlineScreenService",a)};g.Sa(a8,S7);g.h=a8.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Eo=function(a,b,c,d){this.l.contains(a)?this.l.Eo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,O7(this.B,a),d(Error(a)))};
g.h.Rd=function(a){return a?this.g:g.fb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.yB=function(){return(0,g.Xd)(this.Rd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.zB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new T7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(b8(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.HN=function(a,b,c,d){g.dr(L7(this.A,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new u6(f.screen||{});if(!k.name||nra(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);nra(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(b8(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
oe:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);a8.fb.U.call(this)};
g.h.WD=function(){ora(this);this.N("screenChange");this.i.update()};
a8.prototype.dispose=a8.prototype.dispose;g.Sa(d8,g.N);g.h=d8.prototype;g.h.Qn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Ud=function(a){this.fa()||(a&&e8(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){O7(this.R,a)};
g.h.BB=function(){return null};
g.h.Ns=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){e8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Ns("");d8.fb.U.call(this)};g.Sa(f8,d8);g.h=f8.prototype;g.h.Ms=function(a){if(this.g){if(this.g==a)return;e8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);qra(this)};
g.h.ni=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Ud()},this),(0,g.x)(function(){this.Ud(Error("Failed to stop receiver app."))},this)):this.Ud(Error("Stopping cast device witout session."))};
g.h.Ns=g.Ha;g.h.U=function(){this.info("disposeInternal");g.iq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;f8.fb.U.call(this)};
g.h.hM=function(a,b){if(!this.fa())if(b){var c=q6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":pra(this,c.screenId);break;default:e8(this,"Unknown youtube message: "+d)}}else e8(this,"Unable to parse message.")}else e8(this,"No data in message.")};
g.h.kw=function(a,b,c,d){mra(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(e8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.gq((0,g.x)(this.kw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.BB=function(){return this.g};
g.h.IN=function(a){this.fa()||a||(e8(this,"Cast session died."),this.Ud())};g.Sa(g8,d8);g.h=g8.prototype;g.h.Ms=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ni=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ha;g.iq(this.A);this.o?this.o.stop((0,g.x)(this.Ud,this,null),(0,g.x)(this.Ud,this,"Failed to stop DIAL device.")):this.Ud()};
g.h.U=function(){this.g();this.g=g.Ha;g.iq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;g8.fb.U.call(this)};
g.h.LN=function(a){this.fa()||a||(e8(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Ud())};
g.h.Eq=function(a){this.H=A6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,sra(this));a(b);rra(this)}else this.B=(0,g.x)(function(){g.iq(this.A);this.B=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,sra(this));a(c);rra(this)},this),this.A=g.gq((0,g.x)(function(){this.B()},this),100)};
g.h.rE=function(a,b,c){mra(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Qn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Eq(b,c)},this),(0,g.x)(function(d){e8(this,"Failed to get DIAL screen: "+d);
this.Eq(b,c)},this))};g.Sa(h8,d8);h8.prototype.stop=function(){this.Ud()};
h8.prototype.Ms=g.Ha;h8.prototype.ni=function(){g.iq(this.g);this.g=NaN;var a=C6(this.F.Rd(),this.i.label);a?this.Qn(a):this.Ud(Error("No such screen"))};
h8.prototype.U=function(){g.iq(this.g);this.g=NaN;h8.fb.U.call(this)};g.Sa(i8,g.N);g.h=i8.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.QK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.qz,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.eJ,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),$qa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.AB,this)),this.l=ura(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.N("yt-remote-cast2-availability-change",k8(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.RM=function(a,b){j8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)j8("Unsetting old screen status: "+this.g.i.friendlyName),l8(this,null)}if(a&&b){if(!this.g){c=C6(this.i.Rd(),a);if(!c){j8("setConnectedScreenStatus: Unknown screen.");return}var d=tra(this,c);d||(j8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
j8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);l8(this,new h8(this.i,d),!0)}this.g.Ns(b)}else j8("setConnectedScreenStatus: no screen.")};
g.h.SM=function(a){this.fa()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.ni(a):this.Hb("Setting connection data without a session")};
g.h.KN=function(){this.fa()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),l8(this,null)):j8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.qz,this),(0,g.x)(this.nL,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.AB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.w("yt.mdx.remote.debug.handlers_")||[],Xqa);g.qf(this.g);i8.fb.U.call(this)};
g.h.Hb=function(a){O7("Controller",a)};
g.h.rz=function(a,b){this.g==a&&(b||l8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.MK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),j8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)j8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{j8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:l8(this,
new h8(this.i,a));break;case chrome.cast.ReceiverType.DIAL:l8(this,new g8(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:l8(this,new f8(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.eJ=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return j8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);l8(this,new g8(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.rE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Eq,b))};
g.h.qz=function(a){if(!this.fa()){j8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)j8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),l8(this,new f8(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=C6(this.i.Rd(),c.label);d&&v6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(j8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new f8(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.rz,this,this.g)),this.g.ni(null));this.g.Ms(a)}}};
g.h.JN=function(){return this.g?this.g.BB():null};
g.h.nL=function(a){this.fa()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&l8(this,null))};
g.h.QK=function(a){j8("Receiver availability updated: "+a);if(!this.fa()){var b=k8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;k8(this)!=b&&this.N("yt-remote-cast2-availability-change",k8(this))}};
g.h.AB=function(){this.fa()||(this.l=ura(this),j8("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",k8(this)))};
i8.prototype.setLaunchParams=i8.prototype.SM;i8.prototype.setConnectedScreenStatus=i8.prototype.RM;i8.prototype.stopSession=i8.prototype.KN;i8.prototype.getCastSession=i8.prototype.JN;i8.prototype.requestSession=i8.prototype.requestSession;i8.prototype.init=i8.prototype.init;i8.prototype.dispose=i8.prototype.dispose;var r8=[];w8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";x8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Oe=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
w8.prototype.isAdPlaying=function(){return 1081==this.playerState};
w8.prototype.getDuration=function(){return this.u?this.D+y8(this):this.D};
w8.prototype.clone=function(){return new w8(C8(this))};g.t(E8,g.N);g.h=E8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,K8(this,"play")):J8(this,"play"),I8(this,1,A8(F8(this))),this.N("remotePlayerChange")):G8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,K8(this,"pause")):J8(this,"pause"),I8(this,2,A8(F8(this))),this.N("remotePlayerChange")):G8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=F8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,K8(this,"seekTo",{newTime:a}))}else J8(this,"seekTo",{newTime:a});I8(this,3,a);this.N("remotePlayerChange")}else G8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,K8(this,"stopVideo")):J8(this,"stopVideo");var a=F8(this);a.index=-1;a.videoId="";x8(a);H8(this,a);this.N("remotePlayerChange")}else G8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=F8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){O7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){O7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);J8(this,"setVolume",e)}c.muted=b;c.volume=a;H8(this,c)}else G8(this,g.Qa(this.setVolume,a,b))};
g.h.BA=function(a,b){if(1==this.g){var c=F8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.ec(d,c.g));J8(this,"setSubtitlesTrack",d);H8(this,c)}else G8(this,g.Qa(this.BA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();J8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=F8(this);d.audioTrackId=c;H8(this,d)}else G8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=F8(this);c=c||0;var m={videoId:a,currentIndex:c};B8(l,a,c);g.Ca(b)&&(z8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));J8(this,"setPlaylist",m);d||H8(this,l)};
g.h.Wn=function(a,b){if(1==this.g){if(a&&b){var c=F8(this);B8(c,a,b);H8(this,c)}J8(this,"previous")}else G8(this,g.Qa(this.Wn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=F8(this);B8(c,a,b);H8(this,c)}J8(this,"next")}else G8(this,g.Qa(this.nextVideo,a,b))};
g.h.Av=function(){1==this.g?J8(this,"dismissAutoplay"):G8(this,this.Av)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.N.prototype.dispose.call(this)};
g.h.U=function(){Hra(this);this.o=null;this.u.clear();D8(this,null);g.N.prototype.U.call(this)};
g.h.Dt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.JK=function(a,b){this.N(a,b)};
g.h.JI=function(a){if(!a)this.Dk(null),D8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=F8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)O7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,H8(this,b)}};
g.h.Dk=function(a){O7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Ira(this),this.N("remotePlayerChange")};
g.h.II=function(a){a?(Ira(this),this.N("remotePlayerChange")):this.Dk(null)};
g.h.it=function(){J8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.XI=function(){var a=Era();a&&D8(this,a)};
g.h.Hb=function(a){O7("CP",a)};g.t(L8,g.N);g.h=L8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;z8(this.Qa,m);this.o="UNSUPPORTED";M8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,J6())}else M8("Connecting without params"),this.g.connect({},a,J6());Kra(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),N8(this,3));g.N.prototype.dispose.call(this)};
g.h.U=function(){O8(this);Q8(this);P8(this);g.iq(this.B);this.B=NaN;g.iq(this.D);this.D=NaN;this.l=null;g.ns(this.R);this.R.length=0;this.g.dispose();g.N.prototype.U.call(this);this.o=this.A=this.i=this.Qa=this.g=null};
g.h.HD=function(){this.Ph(2)};
g.h.NI=function(){M8("Channel opened");this.I&&(this.I=!1,P8(this),this.H=g.gq((0,g.x)(function(){M8("Timing out waiting for a screen.");this.Ph(1)},this),15E3));
Cqa(Uqa(this.g),this.M)};
g.h.KI=function(){M8("Channel closed");isNaN(this.u)?M6(!0):M6();this.dispose()};
g.h.LI=function(a){M6();isNaN(this.Jj())?(M8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,M8("Channel error: "+a+" with reconnection in "+this.Jj()+" ms"),N8(this,2))};
g.h.MI=function(a){a.params?M8("Received: action="+a.action+", params="+g.Kg(a.params)):M8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=q6(a.params.devices);this.i=(0,g.ge)(a,function(c){return new t6(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Nra(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Nra(this,!1);break;case "remoteConnected":var b=new t6(q6(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||rqa(this.i,b);
break;case "remoteDisconnected":b=new t6(q6(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Pra(this,a);break;case "nowPlaying":Rra(this,a);break;case "onStateChange":Qra(this,a);break;case "onAdStateChange":Sra(this,a);break;case "onVolumeChanged":Tra(this,a);break;case "onSubtitlesTrackChanged":Ora(this,a);break;case "nowAutoplaying":Ura(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Vra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:M8("Unrecognized action: "+a.action)}};
g.h.EM=function(){if(this.l){var a=this.l;this.l=null;this.Qa.videoId!=a&&R8(this,"getNowPlaying")}};
g.h.xD=function(){var a=3;this.fa()||(a=0,isNaN(this.Jj())?J7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Ph=function(a){M8("Disconnecting with "+a);O8(this);this.N("beforeDisconnect",a);1==a&&M6();Vqa(this.g,a);this.dispose()};
g.h.wD=function(){var a=this.Qa;this.l&&(a=this.Qa.clone(),B8(a,this.l,a.index));return C8(a)};
g.h.TM=function(a){var b=new w8(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.l=b.videoId,g.iq(this.B),this.B=g.gq((0,g.x)(this.EM,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&A8(this.Qa)==A8(b)&&g.Kg(this.Qa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.y)(c,function(d){this.N(d)},this)};
g.h.iw=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Jj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.pD=function(){return this.o||"UNSUPPORTED"};
g.h.qD=function(){return this.A||""};
g.h.CN=function(){if(!isNaN(this.Jj())){var a=this.g.i;g.Go(a.g);a.start()}};
g.h.LM=function(a,b){R8(this,a,b);Mra(this)};
L8.prototype.subscribe=L8.prototype.subscribe;L8.prototype.unsubscribeByKey=L8.prototype.Mf;L8.prototype.getProxyState=L8.prototype.xD;L8.prototype.disconnect=L8.prototype.Ph;L8.prototype.getPlayerContextData=L8.prototype.wD;L8.prototype.setPlayerContextData=L8.prototype.TM;L8.prototype.getOtherConnectedRemoteId=L8.prototype.iw;L8.prototype.getReconnectTimeout=L8.prototype.Jj;L8.prototype.getAutoplayMode=L8.prototype.pD;L8.prototype.getAutoplayVideoId=L8.prototype.qD;L8.prototype.reconnect=L8.prototype.CN;
L8.prototype.sendMessage=L8.prototype.LM;g.t(S8,S7);g.h=S8.prototype;g.h.Rd=function(a){return this.Yc.$_gs(a)};
g.h.contains=function(a){return!!this.Yc.$_c(a)};
g.h.get=function(a){return this.Yc.$_g(a)};
g.h.start=function(){this.Yc.$_st()};
g.h.add=function(a,b,c){this.Yc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Yc.$_r(a,b,c)};
g.h.Eo=function(a,b,c,d){this.Yc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Yc.$_ubk(this.i[a]);this.i.length=0;this.Yc=null;S7.prototype.U.call(this)};
g.h.GN=function(){this.N("screenChange")};
g.h.oK=function(){this.N("onlineScreenChange")};
a8.prototype.$_st=a8.prototype.start;a8.prototype.$_gspc=a8.prototype.HN;a8.prototype.$_gsppc=a8.prototype.zB;a8.prototype.$_c=a8.prototype.contains;a8.prototype.$_g=a8.prototype.get;a8.prototype.$_a=a8.prototype.add;a8.prototype.$_un=a8.prototype.Eo;a8.prototype.$_r=a8.prototype.remove;a8.prototype.$_gs=a8.prototype.Rd;a8.prototype.$_gos=a8.prototype.yB;a8.prototype.$_s=a8.prototype.subscribe;a8.prototype.$_ubk=a8.prototype.Mf;var k9=null,j9=!1,T8=null,U8=null,i9=null,Y8=[];g.t(l9,g.A);g.h=l9.prototype;
g.h.U=function(){g.A.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.nz,this);this.g.unsubscribe("remotePlayerChange",this.Fk,this);this.g.unsubscribe("remoteQueueChange",this.Rn,this);this.g.unsubscribe("autoplayUpNext",this.Py,this);this.g.unsubscribe("previousNextChange",this.kz,this);this.g.unsubscribe("nowAutoplaying",this.gz,this);this.g.unsubscribe("autoplayDismissed",this.Oy,this);this.g=this.u=null};
g.h.Lx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(o9(this)){if(!F8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==F8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Qj(c[0],c[1]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();q9(this,0==c?void 0:c);break;case "control_seek":q9(this,c[0]);break;case "control_subtitles_set_track":p9(this,c[0]);break;case "control_set_audio_track":c=c[0],o9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.HI=function(a){this.I.DD(a)};
g.h.mN=function(a){this.Lx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.MA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||p9(this,a)};
g.h.bz=function(a){if(o9(this)){this.g.unsubscribe("remotePlayerChange",this.Fk,this);var b=Math.round(a.volume);a=!!a.muted;var c=F8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.Fk,this)}};
g.h.JJ=function(){g.Xb(this.B)||gsa(this,this.B);this.D=!1};
g.h.nz=function(a,b){this.A.stop();2==b&&this.LA()};
g.h.Fk=function(){if(o9(this)){this.o.stop();var a=F8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Um=1;break;case 1082:case 1083:this.u.Um=0;break;default:this.u.Um=-1}switch(a.playerState){case 1081:case 1:n9(this,new g.RC(8));this.KA();break;case 1085:case 3:n9(this,new g.RC(9));break;case 1083:case 0:n9(this,new g.RC(2));this.H.stop();m9(this,this.i.getVideoData().lengthSeconds);break;case 1084:n9(this,new g.RC(4));break;case 2:n9(this,new g.RC(4));m9(this,A8(a));
break;case -1:n9(this,new g.RC(64));break;case -1E3:n9(this,new g.RC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=F8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,gsa(this,a));a=F8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.mB()}else fsa(this)};
g.h.kz=function(){this.i.N("mdxpreviousnextchange")};
g.h.Rn=function(){o9(this)||fsa(this)};
g.h.KC=function(){this.g.Av()};
g.h.Py=function(a){a&&(a=g.dr("/watch_queue_ajax",{method:"GET",ud:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.PL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.PL=function(a,b){var c=new g.BB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.gz=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Oy=function(){this.i.N("mdxautoplaycanceled")};
g.h.eG=function(a,b){-1==F8(this.g).playerState?q9(this,a):b&&this.g.seekTo(a)};
g.h.mB=function(){if(o9(this)){var a=F8(this.g);this.l.Na(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.K(this.i,"onVolumeChange",this.bz)}};
g.h.KA=function(){this.o.stop();if(!this.g.fa()){var a=F8(this.g);1==a.playerState&&n9(this,new g.RC(8));m9(this,A8(a));this.o.start()}};
g.h.LA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(r9,g.V);r9.prototype.o=function(){s6("mdx-privacy-popup-cancel");this.l.hide()};
r9.prototype.A=function(){s6("mdx-privacy-popup-confirm");this.l.hide()};g.t(s9,g.V);s9.prototype.u=function(a){isa(this,a.state)};g.t(t9,g.tU);t9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.tb(a,this.A,this),g.vU(this,(0,g.ge)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.me(this.A(a)),this.enable(!0)):this.enable(!1)};
t9.prototype.A=function(a){return a.key};
t9.prototype.Ae=function(a){return"cast-selector-receiver"==a?"Cast...":this.B[a].name};
t9.prototype.Lc=function(a){g.tU.prototype.Lc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.ob()};g.t(u9,g.oL);g.h=u9.prototype;
g.h.create=function(){$ra(g.hz(g.X(this.player)));this.o.push(g.nq("yt-remote-before-disconnect",this.DI,this));this.o.push(g.nq("yt-remote-connection-change",this.RK,this));this.o.push(g.nq("yt-remote-receiver-availability-change",this.lz,this));this.o.push(g.nq("yt-remote-auto-connect",this.PK,this));this.o.push(g.nq("yt-remote-receiver-resumed",this.OK,this));this.o.push(g.nq("mdx-privacy-popup-confirm",this.uM,this));this.o.push(g.nq("mdx-privacy-popup-cancel",this.tM,this));this.lz()};
g.h.load=function(){this.player.cancelPlayback();g.oL.prototype.load.call(this);this.u=new l9(this,this.player,this.g);var a=(a=esa())?a.currentTime:0;var b=h9()?new E8(c9(),void 0):null;0==a&&b&&(a=A8(F8(b)));0!=a&&this.Nc(a);hsa(this,this.nk,this.nk);g.vY(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.oL.prototype.unload.call(this);g.vY(this.player.app,5);v9(this)};
g.h.U=function(){g.oq(this.o);g.oL.prototype.U.call(this)};
g.h.bf=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Lx.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Um};
g.h.zD=function(){return this.loaded?this.u.suggestion:null};
g.h.Oe=function(){return this.g?F8(this.g).Oe:!1};
g.h.hasNext=function(){return this.g?F8(this.g).hasNext:!1};
g.h.Nc=function(a,b){this.I=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=F8(this.g),b=this.player.getVideoData();return{allowSeeking:g.O(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.fc():!a.isAdPlaying()&&this.player.fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+y8(a):a.l,isAtLiveHead:1>=(a.u?a.i+y8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+y8(a):a.i,seekableStart:0<a.o?a.o+
y8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Wn=function(){this.g&&this.g.Wn()};
g.h.DI=function(a){1==a&&(this.F=this.g?F8(this.g):null)};
g.h.RK=function(){var a=h9()?new E8(c9(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.F=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.F)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,A8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.lz=function(){this.B=[this.i].concat(bsa());var a=d9()||this.i;w9(this,a);this.player.la("onMdxReceiversChange")};
g.h.oM=function(a){!this.D&&g.cE(a,8)&&(this.player.pauseVideo(),v9(this))};
g.h.PK=function(){var a=d9();w9(this,a)};
g.h.OK=function(){this.l=d9()};
g.h.uM=function(){this.D=!0;v9(this);j9=!1;k9&&f9(k9,1);k9=null};
g.h.tM=function(){this.D=!1;v9(this);w9(this,this.i);this.l=this.i;j9=!1;k9=null;this.player.playVideo()};
g.h.zc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.B;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?u8():w9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.B.length&&"cast-selector-receiver"==this.B[1].key?(b&&u8(),!0):!1}};
g.h.it=function(){this.g.it()};
g.h.Gb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.KV.remote=u9;})(_yt_player);
